name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 20.86.133.25 >> ~/.ssh/known_hosts
        # Ensure correct file permissions for known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Deploy to Azure VM
      run: |
        ssh azureuser@20.86.133.25 'your-deployment-command-here'
